[tool.poetry]
name = "wasp2"
version = "0.1.0"
description = "WASP2: A description of your project"
authors = ["Aaron Ho <aaron.jee.ho@gmail.com>"]
readme = "README.md"
license = "MIT"
packages = [{ include = "wasp2", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.10"
numpy = "2.0.2.*"
pandas = "2.2.3.*"
polars = "1.22.0.*"
scipy = "1.13.1.*"
pysam = "0.23.0.*"
pybedtools = "0.11.0.*"
typer = "0.15.1.*"
anndata = "0.10.9"

[tool.poetry.scripts]
WASP2 = "wasp2.cli:main"

[tool.poetry.group.dev.dependencies]
sphinx = "^8.1.3"
sphinx-book-theme = "^1.1.3"
sphinx-autodoc-typehints = "^3.0.1"
myst-parser = "^4.0.1"
nbsphinx = "^0.9.6"

[build-system]
requires = ["poetry-core>=2.0.1"]
build-backend = "poetry.core.masonry.api"
